### ISSUE TITLE
Sessions need unique URIs

### ISSUE THREAD

**Issue by fuzzyfox** [fuzzyfox/firehug#6]
**Reasons**
- Documentation
- Provide all infromation about a sesion we have (map, badges, tags, description, etc...) in one place
- For facilitators to tweet out / promote their sessions

**Tasks**
- [x] define uri structure for sessions
- [x] scope out individual session view
- [x] add angular controller for individual session view
- [x] create etherpad links based on uri
